### ISSUE TITLE
Turbo still having problems

### ISSUE THREAD

**Issue by midz8** [qbcore-framework/qb-customs#100]
The turbo at my customs is available, but when you apply the turbo it does not stick to the car. I buy the turbo and then leave the menu and go back to the customs and the turbo is there to purchase again. There is no error only a export error which I will include. This the error in tx admin: SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export AddMoney in resource qb-management.

[CitizenFX_log_2022-04-17T233843.log](https://github.com/qbcore-framework/qb-customs/files/8502858/CitizenFX_log_2022-04-17T233843.log)

**Comment by midz8** [comment]
![Desktop Screenshot 2022 04 18 - 13 31 19 34](https://user-images.githubusercontent.com/73448760/163740870-936f4ea0-bd79-464c-b133-597ab1bf6ecc.png)
![Desktop Screenshot 2022 04 18 - 13 31 34 77](https://user-images.githubusercontent.com/73448760/163740878-2b514f35-43eb-4bd5-bb33-6b2fa6768b50.png)
![Desktop Screenshot 2022 04 18 - 13 31 41 12](https://user-images.githubusercontent.com/73448760/163740883-f9792f46-c527-497a-8f10-ea774dd612f6.png)
![Desktop Screenshot 2022 04 18 - 13 31 47 03](https://user-images.githubusercontent.com/73448760/163740890-b8853201-7234-4910-8013-f61f016c8e13.png)
![Desktop Screenshot 2022 04 18 - 13 31 53 66](https://user-images.githubusercontent.com/73448760/163740895-2076e5f0-8778-4254-bfbc-efed3154eb15.png)
![Desktop Screenshot 2022 04 18 - 13 31 59 11](https://user-images.githubusercontent.com/73448760/163740900-cabf6fc1-c850-458b-8acd-3cb0a029c518.png)
![Desktop Screenshot 2022 04 18 - 13 32 05 89](https://user-images.githubusercontent.com/73448760/163740907-79e04763-6c0b-4003-9b23-b477c1887c5f.png)
![Desktop Screenshot 2022 04 18 - 13 32 10 95](https://user-images.githubusercontent.com/73448760/163740913-6daac6bc-5fcd-4a09-be12-8f7bcf3e64c0.png)
![Desktop Screenshot 2022 04 18 - 13 32 18 28](https://user-images.githubusercontent.com/73448760/163740915-e131591a-fc40-4d8a-aafd-caa007c76f5f.png)

**Comment by JonasDev99** [comment]
Can confirm, Turbo does not stick

**Comment by midz8** [comment]
> Can confirm, Turbo does not stick

There is a fix for it in another issue about turbo in the list for qb-customs. Just follow that and it should fix. Its a temporary fix untill they can look more into.

**Comment by ItsANoBrainer** [comment]
Theres already an issue open for this here: https://github.com/qbcore-framework/qb-customs/issues/85

Do not open a second issue if one already exists.

**Comment by midz8** [comment]
> 

Sorry about that. New to this.
