### ISSUE TITLE
Livery problem

### ISSUE THREAD

**Issue by sajjadkarim** [qbcore-framework/qb-customs#101]
In Online There Are Lot's of Livery Available. Some Of Them Says That Doj-tunner Has It But We Like To Use every Customizable And Livery In qb-customs.. Can u Make It if Possible cuz We like to Use Only QB-Core Script.

**Comment by ItsANoBrainer** [comment]
Why Are You Typing Like This. QB Customs has every livery, as it generates it for every vehicle automatically..
