### ISSUE TITLE
Not authorized

### ISSUE THREAD

**Issue by Donnyjohn1** [qbcore-framework/qb-customs#102]
Whenever anyone goes into bennys now we get a little red error “you are not authorized” we have tried switching to every job we have and every vehicle we have with no luck, not 100% sure what else we can do to fix.

**Comment by Donnyjohn1** [comment]
I should add that we also never set it up for job specific upgrades

**Comment by ItsANoBrainer** [comment]
Enable the debug mode in the config and read f8 console to find your issue.

**Comment by QQisLIVE** [comment]
You can also go into the locations file and find the location you're at to check what job is required. There are other restrictions that can be in place as well. Such as Emergency vehicles not allowed to be repaired. Debug mode is the easiest route tho.

**Comment by Donnyjohn1** [comment]
we have tried debug mode but when you try to use it nothing comes up at all in the debug

**Comment by ItsANoBrainer** [comment]
Reinstall from scratch, delete all qb-customs and reinstall. Nobody can replicate this issue and you can not provide any information or debug repro steps for me to assist.

**Comment by Donnyjohn1** [comment]
![20220425125857_1](https://user-images.githubusercontent.com/104074220/165156659-6df1995a-1c72-4c5d-b9ee-d13e3673ef99.jpg)
finally had this error pop up but thats all.

**Comment by ItsANoBrainer** [comment]
Update your qbcore

**Comment by Donnyjohn1** [comment]
![20220425222437_1](https://user-images.githubusercontent.com/104074220/165207228-e748252d-5a99-461a-b3b6-3bd7206cdee8.jpg)
