### ISSUE TITLE
new marker?

### ISSUE THREAD

**Issue by next-game** [qbcore-framework/qb-customs#106]
tell me what is the name of MLO for the new location? the marker is called: "tunershop"
![screenshot31](https://user-images.githubusercontent.com/101860571/164418508-c025c5d1-b949-4d19-a82f-f1fb230eeb81.png)
![tunershop2](https://user-images.githubusercontent.com/101860571/164418514-c973c57e-022b-40fd-b6de-4c87df8e5e26.png)
![tunershop](https://user-images.githubusercontent.com/101860571/164418515-92293f55-3014-4182-a5cf-58a870611318.png)

**Comment by QQisLIVE** [comment]
It's Gabz Tunershop MLO
