### ISSUE TITLE
Car Primary & Secondary Color Change

### ISSUE THREAD

**Issue by MalibuSantez** [qbcore-framework/qb-customs#108]
Since the update I can no longer choose colors, it doesn't matter if I try to change the primary or secondary color. It always stays the same color.
Pearlesence, Interior, Dashboard and Wheelcolors work. Only primary and secondary color is not possible.

Unfortunately, I also have no error message in the server console and no error message in the F8 console.

There is also the problem that you cannot use the same secondary color as the primary unless you buy a different one as a secondary and then switch back to the desired color.

**Comment by ItsANoBrainer** [comment]
What vehicle

**Comment by bbishop56** [comment]
I have a problem with this on the coquette
