### ISSUE TITLE
The DrawText to enter the menu disappears with some cars when car is entered

### ISSUE THREAD

**Issue by Borreke0** [qbcore-framework/qb-customs#109]
Hello,

We have some trouble with the new menu when entering random GTA and non-GTA vehicles.
The menu is always visible outside the car.

But with some cars, when the cars is entered the menu disappears and the menu can't be opened. (We can bypass this with spamming on E when entering the car)
With other cars, we CAN open the menu when the car has ben entered.

Turned the debug on but can't seem to find an issue and I cannot draw the line on why it does work with most of the cars and why it doesn't with some..

It's like 50/50!

**Comment by QQisLIVE** [comment]
It's a problem with the Minimum Z and X Values. Go to your Locations.lua, go to the locations that are having problems and look for the minZ and maxZ. Lower your MinZ and Raise your MaxZ. 
For reference.
![image](https://user-images.githubusercontent.com/59808399/166092355-084698a8-c7ec-47c9-b551-d30dbe128e7c.png)

**Comment by QQisLIVE** [comment]
Inside the Vector3 parameters the Z is 31.0 . So make your minZ about 1 to 2 integers lower and your max z 1 to 2 integers higher.

**Comment by Borreke0** [comment]
Oh, damn! The minZ and maxZ fixed it indeed!

Thanks a lot!
