### ISSUE TITLE
Error with limited cars

### ISSUE THREAD

**Issue by Jackster-2233** [qbcore-framework/qb-customs#111]
With some cars this error comes up - https://i.imgur.com/LoUJVDZ.png

**Comment by Jackster-2233** [comment]
"retinue" is one of the cars

**Comment by Jackster-2233** [comment]
https://www.gta5-mods.com/vehicles/17-aston-martin-db11-hq - this is one of the cars it errors with

**Comment by D4isDAVID** [comment]
@Jackster-2233 
Are you still having this issue?
