### ISSUE TITLE
[Actual Bug] Engine Upgrades don't always work

### ISSUE THREAD

**Issue by rhapidfyre** [qbcore-framework/qb-customs#112]
So essentially what's happening, is Benny's allows you to upgrade the engine up to Upgrade 4. However, not all GTA V vehicles have 4 levels of engine upgrades, they won't have two. For example, the Gauntlet2 (race car version). If you upgrade the engine to Upgrade 4, and race someone with a stock engine, both vehicles will perform equal and you'll cross the line simultaneously, however, if you upgrade to Upgrade 2, you'll smoke the stock car off the line.

Essentially, what I think is happening, is if you upgrade a vehicle's engine passed the maximum upgrade level that vehicle model allows, the game just treats it as a stock engine (0) and you lose all benefits of the upgrades.

Not entirely sure how to fix it, but I believe it would have to do with checking how many upgrade levels the vehicle has before displaying the menu.

**Comment by D4isDAVID** [comment]
Do you know if this is still an issue?
