### ISSUE TITLE
i cant make my new coords work

### ISSUE THREAD

**Issue by Disnione** [qbcore-framework/qb-customs#113]
Hello, im trying to change the coords of bennys to the location of ls custom, but i cant make them work.
![image](https://user-images.githubusercontent.com/105036213/167073025-208244af-3d05-4ba0-aea4-f7ecdb3e6382.png)
Config = Config or {}

Config.Locations = {
    ['Innocence'] = {
        settings = {
            label = 'Bennys',
            welcomeLabel = "Bienvenido a Bennys!",
            enabled = true,
        },
        blip = {
            label = 'Bennys Motorworks',
            coords = vector3(-341.58, -134.63, 39.01),
            sprite = 72,
            scale = 0.65,
            color = 0,
            display = 4,
            enabled = true,
        },
        categories = {
            mods = true,
            repair = true,
            respray = true,
            liveries = true,
            wheels = true,
            tint = true,
            plate = true,
            extras = true,
            neons = true,
            xenons = true,
            horn = true,
            cosmetics = true,
        },
        drawtextui = {
            text = "Bennys Motorworks"
        },
        restrictions = {
            job = { 'mechanic' },
            allowedClasses = {  },
        },
        zones = {
            { coords = vector3(-346.36, -124.95, 38.51), length = 6.0, width = 4.0, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-348.79, -131.58, 38.51), length = 6.0, width = 4.4, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-342.0, -113.97, 38.51), length = 6.0, width = 4.0, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-327.33, -144.25, 38.51), length = 6.0, width = 4.4, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-325.88, -138.91, 38.51), length = 6.0, width = 4.0, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-324.02, -133.74, 38.51), length = 6.0, width = 4.4, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-322.26, -128.54, 38.51), length = 6.0, width = 4.0, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-320.07, -123.49, 38.51), length = 6.0, width = 4.4, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-318.09, -118.21, 38.51), length = 6.0, width = 4.0, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-316.48, -113.17, 38.51), length = 6.0, width = 4.4, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-314.39, -107.82, 38.51), length = 6.0, width = 4.0, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
            { coords = vector3(-312.69, -102.71, 38.51), length = 6.0, width = 4.4, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
        }
    },

Im pasting the part of the code i edited, github did not let me upload the *.lua file.

Thank you

**Comment by Disnione** [comment]
I found the problem, it was the " MaxZ = xx.xx ".
I changed it to 40, and the problem was solve, now i have bennys menu on LSCustom.

hope this can help.

**Comment by xiaoff13** [comment]
> I found the problem, it was the " MaxZ = xx.xx ". I changed it to 40, and the problem was solve, now i have bennys menu on LSCustom.
> 
> hope this can help.

thank you, this helped me
