### ISSUE TITLE
[BUG] Can't access menu!

### ISSUE THREAD

**Issue by FizzGamingJR** [qbcore-framework/qb-customs#116]
**Describe the bug**
Upon creating a new qb-customs location, the popup does not show in a vehicle, but does on foot. Alongside this, it will not allow anybody to access the customisation menu.

**To Reproduce**
1. Add new location in the locations.lua file.
2. Restart server and check in-game.

**Expected behavior**
Popup to show in a vehicle, and menu to open allowing player to change vehicle customisations.

**Screenshots**
![image](https://user-images.githubusercontent.com/28313136/170030431-d1dcf896-c119-41b2-9506-c8c71330af78.png)

![image](https://user-images.githubusercontent.com/28313136/170030508-541db13d-85d4-4da4-8ebb-e808c4fa4695.png)

![image](https://user-images.githubusercontent.com/28313136/170030609-a4926023-b1da-489e-81a2-4ca52aee818d.png)

**Questions (please complete the following information):**
 - When you last updated: 4 Days Ago
 - Are you using custom resource? which ones? No custom resources, tried with qb-target but get same results.
 - Have you renamed `qb-` to something custom? No

**Additional context**
N/A

**Comment by FizzGamingJR** [comment]
I ended up fixing this issue, but now the menu only opens for certain vehicles.
To fix the initial issue I recreated a PolyZone ensuring it is large enough.

Any help to make this work for all cars would be much appreciated!

**Comment by jvmpman** [comment]
How you solve the problem? I have the issue that whenever i enter LSC with a vehivle, the prompt to open the menu with E appears, but when I press E no menu shows up. Same problem when I use radial menu instead of E.

Also this happens at standard LSC Locations, I didn't add a new one.

**Comment by FizzGamingJR** [comment]
> I have almost the same issue, but for me whenever i enter LSC with a vehicle, the prompt to open the menu with E appears, but when I press E no menu shows up. Same problem when I use radial menu instead of E.
> 
> 
> 
> Also this happens at standard LSC locations, I didn't add a new one.

That is not the issue I had, my issue was that the prompt showed up while on foot, but not in a vehicle.
But to answer your question, I made a new polyzone but ensuring that is it big enough and covered the entire area.
I believe my issue was that my previous polyzone was way to small.
