### ISSUE TITLE
[BUG] Stuck in tuning menu

### ISSUE THREAD

**Issue by amgmacht** [qbcore-framework/qb-customs#119]
If I go into the tuning menu of any workshop and then select paintwork, it doesn't show me anything anymore - no colors! I get stuck in the menu and have to restart the script?
I only get errors on the client side in the server console, nothing comes?

https://prnt.sc/vjhYbERGdO5m

**Comment by ItsANoBrainer** [comment]
Make sure your qb-core and qb-customs are properly fully up to date. I can't reproduce this issue.
