### ISSUE TITLE
[BUG] Duplicated Menu Impossible to do anything

### ISSUE THREAD

**Issue by milotiro95** [qbcore-framework/qb-customs#120]
The menu is broken. Impossible to customs any vehicle normally. It duplicate a lot.
![0](https://user-images.githubusercontent.com/86166328/172049796-bd40f639-35c5-45b4-bde5-f35de3a63a4d.png)
![1](https://user-images.githubusercontent.com/86166328/172049798-f3f1cd60-c208-4204-8fd9-f71d846b1c5b.png)

**Comment by ItsANoBrainer** [comment]
Update your QBCore, menuv, and qb-customs. Can not reproduce.
