### ISSUE TITLE
[BUG] black money marked bills at item bugged

### ISSUE THREAD

**Issue by LightUpFam** [qbcore-framework/qb-customs#121]
qbcore black money is set as an item. (illegal activities give you these marked bill bags)

I did make the item so its stackable (via shared lua)

My citizens use black money to gamble with (roll dice)
they also charge others to clean the money
the issue is when they drop the black money or hand it off , the amount vanishes. 
I believe it may loose the value type since they stack now? but im not sure. 

I told everyone to hault on black money transactions till i figure out the bug.  (loosing money)

should I try to set black money up as an account instead like the bank is? and use a give command?
just trying to see how i can accommodate my citizens , thanks

**Comment by ItsANoBrainer** [comment]
This has nothing to do with qb-customs.

**Comment by ItsANoBrainer** [comment]
This has nothing to do with qb-customs.
