### ISSUE TITLE
[BUG] cars getting lost. 

### ISSUE THREAD

**Issue by LightUpFam** [qbcore-framework/qb-customs#122]
player spawns car from garage via Qb garages. 

player drives around.  gets out and goes into a store.

sometimes the car will disappear / despawn 
when I check the database the vehicle state is still 0 like its out. 

when this happens the car ends up Lost.  it does'nt go to impound (2)
and only returns on a server restart to garage. 

I find myself having to go into database to update the state of players cars when they cant find them. 

solutions I was looking at:

I was looking for a qbcore insurance claim script that respawns car with payment but doesnt seem to exist. (only ESX)

I was also looking up vehicle persistence but didnt want to modify too much without being sure.

**Comment by ItsANoBrainer** [comment]
This has nothing to do with qb-customs.
