### ISSUE TITLE
Cannot Customize vehicles but anyone else in the server can [BUG]

### ISSUE THREAD

**Issue by ImMunchie** [qbcore-framework/qb-customs#127]
**Describe the bug**
It seems that I cannot customize any vehicle at all in the menu, It pops up and I can access sit, but I cannot click past the category selection. I am the only one in the server to have this issue and it is across multiple characters not just one. I am also set as a mech on one character and not on the other.

**Expected behavior**
Should be able to click into menu then each category to select the items.

**Comment by ItsANoBrainer** [comment]
Enable debug mode in the config and verify everything is correct there. Check client and server console for errors.
