### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ggoodell2** [qbcore-framework/qb-customs#129]
**Describe the bug**
only first 'location' works

**To Reproduce**
1. only first location in locations.lua works
2. any other locations after that dont work

**Expected behavior**
all locations to work

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: current
 - Are you using custom resource? which ones?no
 - Have you renamed `qb-` to something custom?no

**Additional context**

**Comment by Jamesmayl** [comment]
Everything works, I've gone and checked out every location, and everything works like how it should be.

**Comment by Jamesmayl** [comment]
Hey, @ggoodell2 Can you post a screenshot of you in the harmony auto shop with your car?
