### ISSUE TITLE
Can not create a additional mechanics shop

### ISSUE THREAD

**Issue by midz8** [qbcore-framework/qb-customs#138]
So I have tried to create a additional mechanics to have 2 mechanics in my city but when I go to add the mechanic bays I can see the press E when im standing there but when I hop in a vehicle it does not allow me to press E to work on my vehicle.

**To Reproduce**
1. I have cretaed a new shop in qb-customs/ shared/ loacations.lua. I have inserted all the correct information like the vectors, allowed vehicles, minZ and maxZ.
2. There are no errors

**Expected behavior**
Expected to use the mechanic bays while at the new location created when in a vehicle. 

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] - 3 days ago

 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
I have 2 mechanics. Bennys and jessies performance. Once I tried to create jessies performance It does not allow me to use the mechanic bays to do up any vehicle. I have all vehicles allowed. The bennys works fine but not the new one I have created. 
![Desktop Screenshot 2022 08 25 - 12 39 12 14 (2)](https://user-images.githubusercontent.com/73448760/186548375-85fecdda-ab79-44da-a942-d31cb3abd729.png)

**Comment by ahmed608** [comment]
Have you tried restarting the server?

**Comment by midz8** [comment]
> Have you tried restarting the server?

Of corse. Thats the first thing I would do after doing any changes. We have done everything we can. Im not the only one with this issue as I have this thread on the qbore discord aswell. Just thought Id bring it up here. Not sure if its actually a thing where you cant add extra mechanic bays/shops.

**Comment by D4isDAVID** [comment]
Adding additional shops works just fine. When trying to enter the shop, check your coordinates and make sure that the zones that you configured are correct.

For example, when I tried testing this, on foot I had a Z coordinate of 5, but in a car it was closer to 4. That's most likely the reason you can't enter the shop when in a vehicle.

**Comment by midz8** [comment]
> 

Ahhh I see. Thank you I will give that a go. Cheers

**Comment by midz8** [comment]
Yeah still doesnt help for me. Could you send me a example of your loactions file?

**Comment by D4isDAVID** [comment]
> Yeah still doesnt help for me. Could you send me a example of your loactions file?

I think it's better if you send yours so we can spot what's wrong there

**Comment by midz8** [comment]
[locations.zip](https://github.com/qbcore-framework/qb-customs/files/9424257/locations.zip)
 
Thanks for your help.

**Comment by D4isDAVID** [comment]
Try updating the `minZ` and `maxZ` values to accept Z coordinates from 4-5

**Comment by midz8** [comment]
> Try updating the `minZ` and `maxZ` values to accept Z coordinates froYeah Il give that a go.

**Comment by D4isDAVID** [comment]
Has this been fixed? If so then you can go ahead and close this issue

**Comment by midz8** [comment]
nah it actually hasnt. Ive tried everything.

**Comment by D4isDAVID** [comment]
What is your `locations.lua` file now?

**Comment by midz8** [comment]
What do u mean? This is my location.lua
[locations.zip](https://github.com/qbcore-framework/qb-customs/files/9432896/locations.zip)

**Comment by D4isDAVID** [comment]
Your `minZ` and `maxZ` values are backwards... perhaps that's the issue?

**Comment by midz8** [comment]
I have already tryd to change them around alot. Going off what you said earlier and its still messing up.

**Comment by D4isDAVID** [comment]
Once again, your values are wrong. When I tried using a Coquette to enter the shop, it didn't work, because your `minZ` value was too high. Try setting it to `4.0`.

**Comment by midz8** [comment]
> Once again, your values are wrong. When I tried using a Coquette to enter the shop, it didn't work, because your `minZ` value was too high. Try setting it to `4.0`.

Ok il gve it ago.

**Comment by D4isDAVID** [comment]
Have you fixed it?

**Comment by GhzGarage** [comment]
discord.gg/qbcore
