### ISSUE TITLE
DODAĆ MOŻLIWOŚC PRACY DLA MECHANIKA

### ISSUE THREAD

**Issue by alfiswielki** [qbcore-framework/qb-customs#150]
ADD JOB OPPORTUNITIES FOR MECHANICS
ADD AN OPTION SO THAT ONLY THE MECHANIC CAN DO TUNING

**Comment by D4isDAVID** [comment]
Not sure what you mean by job opportunities, but in the config you can set it up so if mechanics are online only they can use customs.
