### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ckaysone380** [qbcore-framework/qb-customs#157]
### Summary

Updated to latest customs resource - Bug

### Reproduction

go to any customs shop
menu appears for a mere second and doesnt display when in the zone

### Expected behavior

menu only pops in halfway and doesnt appear anymore but custom shop still function

### Actual behavior

Menu doesnt display while sitting  in the zones to customize vehicle

### Last Updated

09/14/2022

### Custom Resources

qb-customs

### Resource Rename

qb-customs

**Comment by D4isDAVID** [comment]
Can you please provide more information? I can't reproduce the issue otherwise.
What does your config look like? Are there any errors?

**Comment by D4isDAVID** [comment]
No response was given and I'm still confused about the issue, but just in case I'll say that the customs menu does not open on it's own. If `UseRadial` is disabled (`false`) in the config then you have to press `E` to enter customs unless manually changed, and if `UseRadial` is enabled (`true`) then you have to open the radial menu (most likely by holding `F1`) and enter customs from there.
