### ISSUE TITLE
[BUG] creating a new location above an interior or subway places the location inside said underground area

### ISSUE THREAD

**Issue by porkandbeans** [qbcore-framework/qb-customs#158]
### Summary

Pasting in direct co-ordinates ignores the Z (height) value if there is an interior below the surface

### Reproduction

1. modify shared/locations.lua to add a new workshop
2. attempt to use the workshop at the new location

### Expected behavior

workshop at the exact co-ordinates
![image](https://user-images.githubusercontent.com/30775997/193393203-53e01110-d543-466b-a2f7-38a5da08a1e8.png)

### Actual behavior

workshop is functional in a sewer beneath the area specified in the co-ordinates
![image](https://user-images.githubusercontent.com/30775997/193393217-1f883055-7c3b-4e3a-9973-74cf1a0a853f.png)

### Last Updated

today

### Custom Resources

none

### Resource Rename

no

**Comment by D4isDAVID** [comment]
Can you show how the zone is configured in `locations.lua`?

**Comment by porkandbeans** [comment]
> Can you show how the zone is configured in `locations.lua`?

```    ['Clubhouse'] = {
        settings = {
            label = 'Lost MC Clubhouse',
            welcomeLabel = "Welcome to Lost MC Clubhouse!",
            enabled = true,
        },
        blip = {
            label = 'Lost MC Clubhouse',
            coords = vector3(980.91, -148.45, 75.05),
            sprite = 72,
            scale = 0.65,
            color = 0,
            display = 4,
            enabled = true,
        },
        categories = {
            mods = true,
            turbo = true,
            repair = true,
            respray = true,
            liveries = true,
            wheels = true,
            tint = true,
            plate = true,
            extras = true,
            neons = true,
            xenons = true,
            horn = true,
            cosmetics = true,
        },
        drawtextui = {
            text = "Lost Vehicle Workshop"
        },
        restrictions = { 
            deniedClasses = { 18 } 
        },
        zones = {
            { coords = vector3(981.92, -112.47, 75.29), length = 6.0, width = 4.0, heading = 270.0, minZ = 29.88, maxZ = 33.48 },
        }
    }

**Comment by D4isDAVID** [comment]
In your zone configuration you have `minZ = 29.88, maxZ = 33.48`, you have to update these values as well.

**Comment by porkandbeans** [comment]
oh right, thank you!
