### ISSUE TITLE
"Not Enough Money"

### ISSUE THREAD

**Issue by tommybtels** [qbcore-framework/qb-customs#17]
Hey, just wondering how to point the script to retrieve data from the players bank account rather than the boss menu?

**Comment by OfficialRDB** [comment]
> 
> 
> Hey, just wondering how to point the script to retrieve data from the players bank account rather than the boss menu?

Yes i'm looking for that too, because right now it keeps saying that i dont have enough money but i 100% have that.

**Comment by tommybtels** [comment]
What was the fix?

**Comment by tommybtels** [comment]
> #18
> That fixed it for me!
What was the fix?
