### ISSUE TITLE
not repairing with the money

### ISSUE THREAD

**Issue by Kromanic** [qbcore-framework/qb-customs#24]
so when i add a locations to my mechanic i can not repair a car with it

**Comment by Kromanic** [comment]
Mechanic Job doesn't let you Repair but when i go to PD it works

**Comment by nggcasey** [comment]
Can confirm.

Mechanic job doesn't let you use upgrades or repair cars - It returns a you don't have enough money message, even though you have enough money. 

Unemployed and police job work fine

**Comment by nggcasey** [comment]
If you have the mechanic job repairs & customization comes out of the society fund, not your own account.

You need to deposit money into the society fund using the boss menu for this to work.
