### ISSUE TITLE
Available mechanic is important

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-customs#26]
Why can the average player repair and upgrade his vehicle
With a mechanic available in the server?
This is a mistake

There must be options inside config
Allowing the citizen to repair his vehicle in the absence of a mechanic
Config.CitizenRepair = true
Allowing the citizen to Upgrade his vehicle in the absence of a mechanic
Config.CitizenUpgrade = true

The number of mechanics available
Config.mechanics = 1

Jobs allowed to repair and upgrade their vehicles in the event of a mechanic
Config.allowjob = {police, ambulance}

All the servers I've been playing with
It has these options

**Comment by Brusein** [comment]
Was this Done somewhere? I was unable to find the config options. Appreciate the assistance.

**Comment by Brusein** [comment]
> Why can the average player repair and upgrade his vehicle With a mechanic available in the server? This is a mistake
> 
> There must be options inside config Allowing the citizen to repair his vehicle in the absence of a mechanic Config.CitizenRepair = true Allowing the citizen to Upgrade his vehicle in the absence of a mechanic Config.CitizenUpgrade = true
> 
> The number of mechanics available Config.mechanics = 1
> 
> Jobs allowed to repair and upgrade their vehicles in the event of a mechanic Config.allowjob = {police, ambulance}
> 
> All the servers I've been playing with It has these options

Was this Done somewhere? I was unable to find the config options. Appreciate the assistance.
