### ISSUE TITLE
It does not modify the car.

### ISSUE THREAD

**Issue by Spaizz** [qbcore-framework/qb-customs#5]
I am modifying the car, although I have money, it does not modify and the mechanic menu does not close. and the menu opens late. I have indicated the error visually. How can I fix it?

![Ekran görüntüsü 2021-07-30 190729](https://user-images.githubusercontent.com/88203594/127680998-b6b73222-2512-49c8-9568-a6b019f11039.png)

**Comment by GhzGarage** [comment]
Seems you are using a different build than is on the github. I would suggest joining the discord and doing a fresh install.
