### ISSUE TITLE
Livery staying when removed

### ISSUE THREAD

**Issue by Sinistermind81** [qbcore-framework/qb-customs#52]
Issue with customs and garage. I bought a elegy retro custom from PDM placed in garage and database showed the mod was 
`"modLivery":-1`
 which was correct (no livery). 

Then went and upgrade the livery and placed in garage and database showed 
`"modLivery":5`
which was correct.

So went back into the custom shop and removed livery and placed back in garage, database still shows 
`"modLivery":5`
So when I pull the car back out of garage, it has the livery on it. 

In the mechanicjob script it comes from this
`RegisterNetEvent('qb-vehicletuning:server:SaveVehicleProps', function(vehicleProps)`
`    if IsVehicleOwned(vehicleProps.plate) then`
`        exports.oxmysql:execute('UPDATE player_vehicles SET mods = ? WHERE plate = ?',`
`           {json.encode(vehicleProps), vehicleProps.plate})`
`    end`
`end)`

Dont know why when selecting stock livery in qb-customs its not writing back the `"modLivery":-1`

**Comment by Sinistermind81** [comment]
so after debugging I have found that any car that uses a livery when set back to "stock livery" the qb-customs does not send the -1 to the database for livery. 

[      script:qb-core] [ qb-core : DEBUG]
[      script:qb-core]  modLivery: 8 
[      script:qb-core] [ END DEBUG ]

**Comment by Deakum** [comment]
I see this is closed however even with latest this is still an issue. Is this being addressed?
