### ISSUE TITLE
Not Enough Money

### ISSUE THREAD

**Issue by istoking** [qbcore-framework/qb-customs#53]
The UI opens and the repair function comes up, but when I try to repair I get "Not Enough Money". I have more than enough cash on me, and much more in the bank, so should work

![Screenshot_1](https://user-images.githubusercontent.com/58592678/147300176-05ca5b44-6105-49a7-bddc-110f882f99eb.png)

**Comment by Reaz93** [comment]
same problem with me, it said "not enough money"

**Comment by Duguayster** [comment]
Same problem here as well

**Comment by istoking** [comment]
> Same problem here as well, no errors generated in console. Also the menu freezes on us a lot and we get stuck in the menu and have to restart the qb-customs script.

have not had it freeze on me, but I am the only one in my city as I slowly develop, so hasn't really had any load on the resource

**Comment by regalonefour** [comment]
also had this issue, had to withdraw all cash from bank and have a player seizecash and it fixed it, haven't looked into but it may be an issue with too much in bank account?

**Comment by Smoke4426** [comment]
If you are set as a mechanic the funds are pulled from the bossmenu fund

**Comment by istoking** [comment]
> If you are set as a mechanic the funds are pulled from the bossmenu fund

wow, can't believe I didn't see that. I can confirm I was set as a mechanic when I was trying this, my bad. I have disabled this now though, as my banking system handles society accounts, not my boss menu.
