### ISSUE TITLE
Not enough money

### ISSUE THREAD

**Issue by balcer64** [qbcore-framework/qb-customs#58]
there is money in cash 600,000 and in the bank (as seen in the screenshot), but writes "Not enough money"
![банк](https://user-images.githubusercontent.com/22128071/148122157-0f46f831-e1ec-4ee7-8ef1-4a386e099d34.png)

**Comment by GhzGarage** [comment]
Comes from mechanic society

**Comment by balcer64** [comment]
> 

thanks, but it's a little confusing)

**Comment by SwftTony** [comment]
if you are a mechanic then it makes you take it from society money but if you are a different job then you will use your money

**Comment by BrandonWainberg-6267** [comment]
just wanted to say thank you for the comment it helped me out immensely
