### ISSUE TITLE
When open UI the ms fire up

### ISSUE THREAD

**Issue by DxMaxi** [qbcore-framework/qb-customs#59]
Everytime i go tune a car in bennys, the qb-customs fire up like this images

https://imgur.com/O1LyDs7

https://imgur.com/SdkHTHU

https://imgur.com/kcqCy8Z

**Comment by SwftTony** [comment]
Did you change the code in any way at all and how many times has this happened to you

**Comment by DxMaxi** [comment]
> Did you change the code in any way at all and how many times has this happened to you

No, its default. This happens everytime i open the menu

**Comment by SwftTony** [comment]
did you change anything in the menu/core

**Comment by SwftTony** [comment]
Can not replicate error had more than one person try and reticulate it and there is no error you must have changed something on your side or be on an outdated version.

**Comment by ItsANoBrainer** [comment]
Update your qb-core and or qb-customs, can't reproduce.
