### ISSUE TITLE
Money Issue

### ISSUE THREAD

**Issue by baytowntexas** [qbcore-framework/qb-customs#61]
i am going to the shop to customize and it say i have no money

**Comment by ghost-george** [comment]
add money to the mechanic society in the boss menu as the highest job grade and that should fix your problem

**Comment by baytowntexas** [comment]
That’ll fix the issue with no being able to repair.? I go in to upgrade or repair and it says I have no money in cash or bank


Sent from Yahoo Mail for iPhone


On Friday, January 28, 2022, 4:11 PM, ghost-george ***@***.***> wrote:




add money to the mechanic society in the boss menu as the highest job grade and that should fix your problem

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cynicalmars** [comment]
I learnt that if you have a mechanic active then benny's won't work

**Comment by xViperAG** [comment]
I'm also having an issue as well, that even as the highest mechanic role you can't fix or change anything on the car. It gives me the same error of Not Enough Money.

https://i.imgur.com/a5zzzpR.jpeg
