### ISSUE TITLE
Script Error on Livery Select

### ISSUE THREAD

**Issue by L1onqk** [qbcore-framework/qb-customs#63]
Nothing appears after selection, only an error message
![Screenshot_1](https://user-images.githubusercontent.com/98112761/151698075-603be408-4357-4072-91c4-6884053fe0e9.png)
![Screenshot_2](https://user-images.githubusercontent.com/98112761/151698077-f93dab84-207c-4790-a7d4-ece0de604a52.png)

**Comment by kran3ns** [comment]
Same for me

**Comment by Richyy11x** [comment]
Yep Same here, Looks like quite a few people have this issue, not sure there has been a solution yet

**Comment by ItsANoBrainer** [comment]
This only happens on emergency vehicles, a fix has been pushed for it in the next version. 

Just comment out the check of its Class emergency or not.

https://github.com/qbcore-framework/qb-customs/pull/71
