### ISSUE TITLE
Stuck in custom menu after first mod

### ISSUE THREAD

**Issue by Pojus** [qbcore-framework/qb-customs#68]
After the qb-management I've noticed that after the first mod applyed to the car (only if you're mechanic) you get stuck with the custom menu with this error in console:

> [   script:qb-customs] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export GetAccount in resource qb-bossmenu

```
        balance = exports['qb-bossmenu']:GetAccount(Player.PlayerData.job.name)
```

**Comment by KingMilk8** [comment]
Any luck with the fix for this? Have tried to alter the CORE files to no avail.

**Comment by GhostLegionRP** [comment]
edit qb-bossmenu to qb-management in sv_bennys.lua

**Comment by Pojus** [comment]
> edit qb-bossmenu to qb-management in sv_bennys.lua

That was so simple! It worked perfectly! Thanks GhostLegionRP

**Comment by kran3ns** [comment]
> edit qb-bossmenu to qb-management in sv_bennys.lua

Does not work for me though
