### ISSUE TITLE
Livery

### ISSUE THREAD

**Issue by Rav3n95** [qbcore-framework/qb-customs#73]
Hey Fellas! 

Basically when you apply a livery to the car let't say example Sultan RS, lets say livery number 7. Then place it to any garage, come back try to remove the livery. Car be fine no livery on it at all. But its not saved to the database. If you get the modLivery after apply stock livery still getting number 7 back.

**Comment by ItsANoBrainer** [comment]
Should be fixed with https://github.com/qbcore-framework/qb-customs/pull/71 (which is now live). Please try again and let us know if you're still having issues.
