### ISSUE TITLE
freeze

### ISSUE THREAD

**Issue by SeriumTW** [qbcore-framework/qb-customs#74]
![image](https://user-images.githubusercontent.com/79084923/159810956-d4c650ce-b695-4c04-b90d-8ec526a82391.png)
when you go to a category with modifications not supported by the vehicle the script crashes
![image](https://user-images.githubusercontent.com/79084923/159811096-77a4cae9-0e32-4cdc-8fe9-be49ef43e9ae.png)

**Comment by ItsANoBrainer** [comment]
Fixed in https://github.com/qbcore-framework/qb-customs/pull/71
