### ISSUE TITLE
Livery issue still happening

### ISSUE THREAD

**Issue by Rav3n95** [qbcore-framework/qb-customs#76]
Hey, So apparently livery issue still happening. 

Maybe i was not clear enough. 
So basically you get your non livery car modLivery: -1 to the custom, i used Vectre. Select exemple modLivery: 14. Save it to the garage, once you get your car from garage whit livery on everything fine. Soonest you go to customs to remove it. Its removeit visually only. If you get modLivery instead of -1 its still 14. Even if you save it 100 times liveryindex will be 14. 

Also if you change it to modLivery: 1 will save it perfectly. 

I did a quick fix command to my server for that. 
Client: 
```lua
RegisterCommand('removelivery', function()
    local plyPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(plyPed, false)
    if veh ~= 0 then
        local myCar = QBCore.Functions.GetVehicleProperties(veh)
        TriggerServerEvent('qb-garages:server:removeLivery', myCar)
        QBCore.Functions.DeleteVehicle(veh)
    end
end)
```

Server: 
```lua 
RegisterNetEvent("qb-garages:server:removeLivery", function(myCar)
    local src = source
    if IsVehicleOwned(myCar.plate) then
        myCar['modLivery'] = -1
        MySQL.Async.execute('UPDATE player_vehicles SET mods = ?, state = ? WHERE plate = ?', {json.encode(myCar), 1, myCar.plate})
    end
end)
```

**Comment by Rav3n95** [comment]
Also, ill download a totally fress server to test it out.

**Comment by Rav3n95** [comment]
Update: Happening on the brand new server too

**Comment by Rav3n95** [comment]
Also [https://i.imgur.com/4E4xIa8.png](url)

**Comment by ItsANoBrainer** [comment]
This has nothing to do with qb-customs, this was a bug in qb-core.

https://github.com/qbcore-framework/qb-core/pull/597

Fix has been merged into main.
