### ISSUE TITLE
Cannot use customs with a job.

### ISSUE THREAD

**Issue by DannysRP** [qbcore-framework/qb-customs#79]
**Description:**
I cannot use a customs location that requires you to have a job. The radial menu option shows up but when you click "Enter customs" it doesn't do anything. No error in F8 or console. It also does not work using with radial menu option set to false. The other locations that aren't defined by a job seem to work fine.

**Comment by ItsANoBrainer** [comment]
Works fine for me. Show me your config. Did you update to the latest version?

**Comment by DamziDDK** [comment]
> **Description:** I cannot use a customs location that requires you to have a job. The radial menu option shows up but when you click "Enter customs" it doesn't do anything. No error in F8 or console. It also does not work using with radial menu option set to false. The other locations that aren't defined by a job seem to work fine.

Mee too after i update to the newest qb-customs :(

**Comment by DannysRP** [comment]
Yeah I just have a fresh install of qb-customs

**Comment by DamziDDK** [comment]
> Yeah I just have a fresh install of qb-customs

Even fresh install of the newest qb-customs it still doens't work.

**Comment by ItsANoBrainer** [comment]
Copy paste or attach the location settings to your comments. I need more information than "it doesn't work".

**Comment by ItsANoBrainer** [comment]
Danny's issue was misconfigured config, nothing was wrong with this script.
