### ISSUE TITLE
performance options don't show

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-customs#80]
its something I've been saying for a week now in the PR, the early vison worked. but as the week went on it stopped.. that performance options don't show. and yes I have the latest version. and I've tried it with no edits.  with and with out radial true/false and 1/0

it only shows these options. 

<a href="https://imgbb.com/"><img src="https://i.ibb.co/swBSr5n/ben.png" alt="ben" border="0"></a>

<a href="https://imgbb.com/"><img src="https://i.ibb.co/fHxqPJN/ben2.png" alt="ben2" border="0"></a>

**Comment by ItsANoBrainer** [comment]
https://github.com/qbcore-framework/qb-customs/issues/78

**Comment by Andyauk** [comment]
> Did you even read the comment I left in your last issue request?
> 
> [#78 (comment)](https://github.com/qbcore-framework/qb-customs/issues/78#issuecomment-1081164042)

I did, but it was closed so I couldn't find it. 

I noticed, its not listed in the location config.

```
        categories = {
            repair = true,
            respray = true,
            liveries = true,
            wheels = true,
            tint = true,
            plate = true,
            extras = true,
            neons = true,
            xenons = true,
            horn = true,
        },
```

**Comment by Andyauk** [comment]
so I will just add it in. mods = true, thanks sorry to be a pain. you can close it now. thanks.
