### ISSUE TITLE
qb-customs update not working.

### ISSUE THREAD

**Issue by DamziDDK** [qbcore-framework/qb-customs#83]
ive been updating all my ressource with the newest from qbcore, and im getting alot of errors, this is one of them.
https://i.imgur.com/aTveLlZ.png

**Comment by izMystic** [comment]
your [qb-core](https://github.com/qbcore-framework/qb-core) resource isnt updated

**Comment by DamziDDK** [comment]
> your [qb-core](https://github.com/qbcore-framework/qb-core) resource isnt updated

i mean i took the lastest update: https://github.com/qbcore-framework/qb-core

**Comment by DamziDDK** [comment]
> then you would have those exports

im not the best dev so i just w8 for qb-core update :)

**Comment by DamziDDK** [comment]
> what? its already updated with them

okay them im blind could you guide me where to look? :)

**Comment by izMystic** [comment]
the fact you dont have them, means you dont have the most updated version

**Comment by DamziDDK** [comment]
> the fact you dont have them, means you dont have the most updated version

Ehmm i could try to get a fresh qb-core and start over, do i also need qb-drawtext or that is no need?

**Comment by izMystic** [comment]
try and delete your current qb-core resource, download the most recent one then put that it, restart your server then check, and no you dont need qb-drawtext

**Comment by DamziDDK** [comment]
> try and delete your current qb-core resource, download the most recent one then put that it, restart your server then check, and no you dont need qb-drawtext

Alright ill try that thanks for you time and help :)
