### ISSUE TITLE
Changing Locations 

### ISSUE THREAD

**Issue by DsyRzGaming** [qbcore-framework/qb-customs#84]
I Change the locations coord to a new MLO that i want to use in my server and the blip change but wen i try to customize the vehicle things pop up to open the menu 
![20220330012808_1](https://user-images.githubusercontent.com/102648715/160765751-b394844a-1216-404a-95b2-8d3cfbcb5d26.jpg)

**Comment by GhzGarage** [comment]
Join the discord, i think there is something else going on. discord.gg/qbcore

**Comment by DsyRzGaming** [comment]
> Join the discord, i think there is something else going on. discord.gg/qbcore

Is not letting me join the Discord
