### ISSUE TITLE
Turbo

### ISSUE THREAD

**Issue by QQisLIVE** [qbcore-framework/qb-customs#85]
I've been attempting to fix this with the little knowledge that I have and found a solution which is good enough for me.
The Issue:
Turbo buttons work, however when you use the "enable" button I think the button "removes" the turbo. so you're actually not installing it.

These are the fixes that I applied, but I don't think it's the correct solution.

![image](https://user-images.githubusercontent.com/59808399/161137528-6aabc25e-5d62-488c-8554-48a760c67917.png)
![image](https://user-images.githubusercontent.com/59808399/161137680-00cc7f10-0ed4-4ec8-aeea-c81c9adb68c0.png)

The only issue with this, is that the "Enabled" is now up top and "Disable" is on the bottom. They are flipped.

**Comment by midz8** [comment]
Hi so i have the same problem. I go topress on the turbo and purchase. i leave the menu and go back into the menu only to see that the turbo needs to be purchased again. would this help fix my issue?

**Comment by midz8** [comment]
Thank you so much for your help. This fixed my issue.

**Comment by JonasDev99** [comment]
How did you fix it?

**Comment by midz8** [comment]
> How did you fix it?

This is the fix. Just copy what it shows in the images. I beleive and changed around the -1 and 0 for both images. Thats the fix.

**Comment by midz8** [comment]
Please confirm when you have edited that it does work.

**Comment by midz8** [comment]
I beleive theres 2 of the same issue in the forum that you may have to close too. @ItsANoBrainer 
for the neons lol.

**Comment by ItsANoBrainer** [comment]
Yeah I'm looking at a bunch of these issues today.

**Comment by ItsANoBrainer** [comment]
Fixed with https://github.com/qbcore-framework/qb-customs/pull/105
