### ISSUE TITLE
Addition: Remove $ from BossMenu Factions 

### ISSUE THREAD

**Issue by QQisLIVE** [qbcore-framework/qb-customs#86]
Just looking for an addition to be able to remove money from a factions bank account. 

Example:

If I have several jobs in the server utilizing the bennys for upgrades or cosmetics, the cost would come out of that jobs account.

**Comment by flitzx** [comment]
I would really love this to! Right now the mechanics needs to pay for everything from their own pockets

**Comment by Brusein** [comment]
Yeah my mechanics that have a different boss account / job title pay out of pocket and tack it onto the charge for the customer.

**Comment by Dabcity** [comment]
Yeah, this needs to be added. Right now you have the ability to create new customs with new jobs attached to them, but all the money just get funneled back to Mechanic, code pays out to mechanic job instead of checking for jobrole and paying to that funds in qb management.

**Comment by 19adorest** [comment]
Try this one..
```
elseif type == "performance" or type == "turbo" then
        if balance >= vehicleCustomisationPrices[type].prices[upgradeLevel] then
            TriggerClientEvent('qb-customs:client:purchaseSuccessful', source)
            -- Player.Functions.RemoveMoney(moneyType, vehicleCustomisationPrices[type].prices[upgradeLevel], "bennys")
	exports['qb-management']:RemoveMoney("mechanic", vehicleCustomisationPrices[type].prices[upgradeLevel])
        else
            TriggerClientEvent('qb-customs:client:purchaseFailed', source)
        end
    else
        if balance >= vehicleCustomisationPrices[type].price then
            TriggerClientEvent('qb-customs:client:purchaseSuccessful', source)
            -- Player.Functions.RemoveMoney(moneyType, vehicleCustomisationPrices[type].price, "bennys")
        exports['qb-management']:RemoveMoney("mechanic", vehicleCustomisationPrices[type].price)
        else
            TriggerClientEvent('qb-customs:client:purchaseFailed', source)
        end
    end
```

**Comment by nzkfc** [comment]
The update to having multiple locations is a really nice touch, it helps so much to have all the configs for vehicle class and menu restrictions so very much a step in the right direction. However I think theres an oversight on how most cities setup their business roleplay, most won't have one mechanic company and then say several branches, instead it's one company per location, so the removal of being able to target the society account is a biggie to lose.

I've tried the above and changintg things like `Player.Functions.RemoveMoney(moneyType, repairCost, player.playerdata.job.name)` but still can't get it working. The menu either locks up or it just uses bank.
