### ISSUE TITLE
DrawText export

### ISSUE THREAD

**Issue by kaidenkhant** [qbcore-framework/qb-customs#89]
![image](https://user-images.githubusercontent.com/64560839/161459018-f78cf981-dc6e-49c0-8863-d123c3e5894f.png)
The export in qb-customs is:
`exports['qb-core']:DrawText(text, 'left')`

while the function in qb-core is:
`function QBCore.Functions.DrawText(x, y, width, height, scale, r, g, b, a, text)
    -- Use local function instead
    SetTextFont(4)
    SetTextProportional(0)
    SetTextScale(scale, scale)
    SetTextColour(r, g, b, a)
    SetTextDropShadow(0, 0, 0, 0, 255)
    SetTextEdge(2, 0, 0, 0, 255)
    SetTextDropShadow()
    SetTextOutline()
    SetTextEntry('STRING')
    AddTextComponentString(text)
    DrawText(x - width / 2, y - height / 2 + 0.005)
end`

**Comment by Luma-exe** [comment]
Have you fixed this?

**Comment by kaidenkhant** [comment]
> Have you fixed this?

Yes, I was missing the drawtext.lua in qbcore resource. Just push that qbcore update
