### ISSUE TITLE
[Script Error]

### ISSUE THREAD

**Issue by erayko-dev** [qbcore-framework/qb-customs#90]
I have installed it and I am running latest version of qbcore, mech blips appear on the map but no option to modify the car and PD one gives me this error (the only error which appears) and I do have the PD role, please help:

![image](https://user-images.githubusercontent.com/76734458/161960847-bb96866c-4879-4da1-8d41-aa02d3d66732.png)

**Comment by GhzGarage** [comment]
You need to update your core to include drawtext
