### ISSUE TITLE
Money from society account

### ISSUE THREAD

**Issue by solarix0** [qbcore-framework/qb-customs#93]
Would like that costs of upgrades pulls money from society funds instead of personal account

**Comment by kaidenkhant** [comment]
yes please, 'society' doesnt work anymore

**Comment by og23rd** [comment]
Would love to see this

**Comment by Dabcity** [comment]
Kinda needs to be addressed in my opinion, all these new shops but all the money just goes to mechanic.

**Comment by ItsANoBrainer** [comment]
https://github.com/qbcore-framework/qb-customs/issues/86
