### ISSUE TITLE
Customs Menu still gets stuck

### ISSUE THREAD

**Issue by SwagCityRP** [qbcore-framework/qb-customs#94]
Just so you know I am digging through the code to try and figure out why this would happen but I'm pretty new to this framework (and Lua in general, although not with software development). If there's any hints on where to look for this, I'd appreciate it.

Using latest qb-core, qb-management, and qb-customs. Pretty easy to replicate but not seeing any error messages, even with Config.Debug = true. Earlier threads with no apparent answers:

* #68 
* #62 

There's also several questions/threads in discord that are unanswered.

What it looks like in game - after I press enter, nothing happens, menu is completely stuck, and no error messages in console. Can't move, if you try to drive the engine will rev but not move. Can't exit the menu. But you're basically stuck there.

![image](https://user-images.githubusercontent.com/103213207/162648921-bed471f7-f1ba-4792-8062-fa3fcc384e04.png)

Log:

`
[   6912390] [b2372_GTAProce]             MainThrd/ ***************************************************************************
[   6912390] [b2372_GTAProce]             MainThrd/ Restriction Debug
[   6912390] [b2372_GTAProce]             MainThrd/ ***************************************************************************
[   6912390] [b2372_GTAProce]             MainThrd/ Is Enabled: true
[   6912390] [b2372_GTAProce]             MainThrd/ Vehicle: 9258498
[   6912390] [b2372_GTAProce]             MainThrd/ allowedJob: true
[   6912390] [b2372_GTAProce]             MainThrd/ allowedGang: true
[   6912390] [b2372_GTAProce]             MainThrd/ allowedClass: true
[   6912390] [b2372_GTAProce]             MainThrd/ ***************************************************************************
[   6912390] [b2372_GTAProce]             MainThrd/ ***************************************************************************
[   6912390] [b2372_GTAProce]             MainThrd/ EnterLocation Debug Start | CanEnter: true | Repair Only: false | Override: null
[   6912390] [b2372_GTAProce]             MainThrd/ ***************************************************************************
[   6912390] [b2372_GTAProce]             MainThrd/ blip	{"color":0,"enabled":true,"sprite":72,"scale":0.65,"label":"Bennys Motorworks","display":4,"coords":{"x":-205.69920349121095,"y":-1312.7376708984376,"z":31.15880012512207}}
[   6912390] [b2372_GTAProce]             MainThrd/ restrictions	{"deniedClasses":[18]}
[   6912390] [b2372_GTAProce]             MainThrd/ zones	[{"coords":{"x":-212.5500030517578,"y":-1320.56005859375,"z":31.0},"length":6.0,"heading":270.0,"maxZ":33.48,"minZ":29.88,"width":4.0},{"coords":{"x":-222.47000122070313,"y":-1329.72998046875,"z":31.0},"length":6.0,"heading":270.0,"maxZ":33.48,"minZ":29.88,"width":4.0}]
[   6912390] [b2372_GTAProce]             MainThrd/ categories	{"wheels":true,"liveries":true,"extras":true,"respray":true,"horn":true,"repair":true,"tint":true,"xenons":true,"plate":true,"neons":true,"mods":true,"cosmetics":true}
[   6912390] [b2372_GTAProce]             MainThrd/ settings	{"enabled":true,"welcomeLabel":"Welcome to Benny's Motorworks!","label":"Bennys Motorworks"}
[   6912390] [b2372_GTAProce]             MainThrd/ drawtextui	{"text":"Bennys Motorworks"}
[   6912390] [b2372_GTAProce]             MainThrd/ respray	true
[   6912390] [b2372_GTAProce]             MainThrd/ turbo	false
[   6912390] [b2372_GTAProce]             MainThrd/ cosmetics	true
[   6912390] [b2372_GTAProce]             MainThrd/ repair	true
[   6912390] [b2372_GTAProce]             MainThrd/ extras	true
[   6912390] [b2372_GTAProce]             MainThrd/ liveries	true
[   6912390] [b2372_GTAProce]             MainThrd/ xenons	true
[   6912390] [b2372_GTAProce]             MainThrd/ wheels	true
[   6912390] [b2372_GTAProce]             MainThrd/ tint	true
[   6912390] [b2372_GTAProce]             MainThrd/ plate	true
[   6912390] [b2372_GTAProce]             MainThrd/ mods	true
[   6912390] [b2372_GTAProce]             MainThrd/ neons	true
[   6912390] [b2372_GTAProce]             MainThrd/ armor	false
[   6912390] [b2372_GTAProce]             MainThrd/ horn	true
[   6912390] [b2372_GTAProce]             MainThrd/ ***************************************************************************
[   6912390] [b2372_GTAProce]             MainThrd/ EnterLocation Debug End
[   6912390] [b2372_GTAProce]             MainThrd/ ***************************************************************************
`

**Comment by SwagCityRP** [comment]
Small note that might help hunting this down -- I died (from starvation), did /revive, got out of the car, did a 'restart qb-customs', was able to get back into the car and drive away, with the modification applied:

![image](https://user-images.githubusercontent.com/103213207/162649295-23174520-a734-4606-ba3c-2e00c6153f49.png)

**Comment by SwagCityRP** [comment]
Further research is showing that the "qb-customs:server:attemptPurchase" event isn't firing when this breaks:

![image](https://user-images.githubusercontent.com/103213207/162651076-87bf0209-4d5e-4aa4-9d19-0a7c22f6a8e1.png)
![image](https://user-images.githubusercontent.com/103213207/162651094-d153b7c5-7e2b-4f1e-9aea-17b5be2bc817.png)

When the purchase is successful and the menu works, that's what we see.

So we're getting stuck here:
![image](https://user-images.githubusercontent.com/103213207/162651154-321f01b4-8cf3-457a-82ea-c440fc2efe6e.png)

Because TriggerServerEvent("qb-customs:server:attemptPurchase", type, upgradeLevel) is never firing.

**Comment by SwagCityRP** [comment]
Testing it like this -

![image](https://user-images.githubusercontent.com/103213207/162652385-1f427592-1f84-449b-8b5d-b73807c473ce.png)

It's succeeding like 1 out of every 10-15 tries, haha.

**Comment by SwagCityRP** [comment]
Nasty short term fix, just so that my server can use the customs shops:

Set a local variable in cl_bennys named "isPurchasing"

Added this to the AttemptPurchase function:

`
    attemptingPurchase = true
    isPurchasing = false

    while attemptingPurchase do
        Wait(1)
        if isPurchasing == false then
            TriggerServerEvent("qb-customs:server:attemptPurchase", type, upgradeLevel)
        end
    end
`

Also added to cl_bennys (formatting is off):

`
    RegisterNetEvent("qb-customs:client:purchasing", function()
        isPurchasing = true
    end)
`

Then added

` TriggerClientEvent('qb-customs:client:purchasing', source) `

Into the attemptPurchase RegisterNetEvent at the top.

I'm not going to PR this because this is not a fix, this is a hack that spams attemptPurchase until it actually activates. Weird bug.

**Comment by ItsANoBrainer** [comment]
Any server side errors?

**Comment by ItsANoBrainer** [comment]
Reinstall from scratch, delete all qb-customs and reinstall. Make sure EVERYTHING is updated. Look for errors in server console.

**Comment by Flek26** [comment]
Was there every a fix for this? Still happens
