### ISSUE TITLE
Under glow neons not working

### ISSUE THREAD

**Issue by jmilanek** [qbcore-framework/qb-customs#95]
The neons work until a car is placed in garage and taken out and then it is not there anymore.

**Comment by daddyDUBZ** [comment]
This would indicate an issue with the script storing the vehicle IMO  i.e. your garage.  Maybe check there, my underflow and neon's seem to be functional.

**Comment by midz8** [comment]
Hi did you find a fix for this?

**Comment by ItsANoBrainer** [comment]
Fixed with latest QBCore update.

**Comment by jmilanek** [comment]
Not yet. It seems to stick just doesn’t show once out of garage!


Sent from Yahoo Mail for iPhone


On Wednesday, April 20, 2022, 7:55 PM, midz8 ***@***.***> wrote:




Hi did you find a fix for this?
